# the compiler: gcc for C program, define as g++ for C++
CC = gcc

# the build target executable:

all: $(TARGET)

$(TARGET): $(TARGET).c
		$(CC) -o $(TARGET) $(TARGET).c $(SOURCES)

clean:
		$(RM) $(TARGET) *.o

problem_1: problem_1.c
		$(CC) -o problem_1.o problem_1.c

problem_1_run: problem_1
		./problem_1.o
		make clean


problem_3: problem_3.c
		$(CC) -o problem_3.o problem_3.c

problem_3_run: problem_3
		./problem_3.o
		make clean

problem_4: problem_4.c
		$(CC) -o problem_4.o problem_4.c

problem_4_run: problem_4
		./problem_4.o
		make clean

		

problem_5: problem_5.c
		$(CC) -o problem_5.o problem_5.c

problem_5_run: problem_5
		./problem_5.o
		make clean

problem_6: problem_6.c
		$(CC) -o problem_6.o problem_6.c

problem_6_run: problem_6
		./problem_6.o
		make clean

problem_7: problem_7.c
		$(CC) -o problem_7.o problem_7.c

problem_7_run: problem_7
		./problem_7.o
		make clean


problem_8: problem_8.c
		$(CC) -o problem_8.o problem_8.c

problem_8_run: problem_8
		./problem_8.o
		make clean


problem_9: problem_9.c
		$(CC) -o problem_9.o problem_9.c

problem_9_run: problem_9
		./problem_9.o
		make clean


problem_10: problem_10.c
		$(CC) -o problem_10.o problem_10.c

problem_10_run: problem_10
		./problem_10.o
		make clean