#include "hashtable.h"

#include <stdio.h>

void main()
{
    InitHashTable();
    InsertData("Hello", "Hi");
    InsertData("Mobile", "Phone");
    InsertData("Accomplish", "Achieve");
    InsertData("Attain", "Suceed");
    InsertData("Accomplish", "	Achieve or complete successfully");
    InsertData("Attain", "	Succeed in achieving");
    InsertData("Adapt", "	Make something suitable for a new use or purpose");
    InsertData("Affordable", "	Reasonably priced");
    InsertData("Accompany", "	go somewhere with someone as a companion");
    InsertData("Analyse", "	examine methodically and in detail");
    InsertData("Admire", "	regard an object quality or person with respect or warm approval");
    InsertData("Associate", "	connect someone or something with something else in one’s mind");
    InsertData("Artificial", "	made by human beings rather than occurring naturally");
    InsertData("Apparently", "	as far as one knows or can see");

    InsertData("Beside", "	at the side of");
    InsertData("Beside", "at the side of; next to");
    InsertData("Balance", "an even distribution of weight enabling someone or something to remain upright and steady");
    InsertData("Benefit", "an advantage or profit gained from something");
    InsertData("Boundary", "a line that marks the limits of an area");
    InsertData("Borrow", "take and use something that belongs to someone else with the intention of returning it");
    InsertData("Better", "of a more excellent or effective type or quality");
    InsertData("Babysitting", "the care of a child or children while the parents are out");

    InsertData("Confuse", "cause someone to become bewildered or perplexed");
    InsertData("Cordially", "in a warm and friendly way");
    InsertData("Chase", "pursue in order to catch or catch up with");
    InsertData("Cast", "register");
    InsertData("Conference", "a formal meeting for discussion");
    InsertData("Challenge", "a call to take part in a contest or competition especially a duel");
    InsertData("Dare", "have the courage to do something");
    InsertData("Delete", "remove or obliterate");
    InsertData("Defend", "resist an attack made on someone or something");
    InsertData("Detect", "discover or identify the presence or existence of");
    InsertData("Detach", "leave or separate oneself from");
    InsertData("Gaze", "look steadily and intently");
    InsertData("Game", "a competitive form of play played according to rules and decided by skill strength or luck");
    InsertData("Gorgeous", "very attractive");
    InsertData("Destroy", "put an end to the existence of something by damaging or attacking it");
    InsertData("Differentiate", "recognize or ascertain what makes someone or something different");
    InsertData("Discrimination", "the unjust or prejudicial treatment of different categories of people or things especially on the grounds of race age or sex");
    InsertData("Distinguish", "recognize or treat someone or something as different");
    InsertData("Efficient", "achieving maximum productivity with minimum wasted effort or expense");
    InsertData("Effective", "successful in producing a desired or intended result");
    InsertData("Enormous", "very large in size quantity or extent");
    InsertData("Evidence", "the available body of facts or information indicating whether a belief or proposition is true or valid");
    InsertData("Eliminate", "completely remove or get rid of something");
    InsertData("Engagement", "an arrangement to do something or go somewhere at a fixed time");
    InsertData("Elementary", "relating to the basic elements of a subject");
    InsertData("Enigmatic", "difficult to interpret or understand");
    InsertData("Friction", "conflict or animosity caused by a clash of wills temperaments or opinions");
    InsertData("Fraction", "a small or tiny part of something");
    InsertData("Function", "an activity or purpose natural to or intended for a person or thing");
    InsertData("Fund", "a sum of money saved or made available for a particular purpose");
    InsertData("Frequent", "happening often");
    InsertData("Fable", "a short story typically with animals as characters conveying a moral");
    InsertData("Fabulous", "extraordinary");
    InsertData("Fantastic", "extraordinarily good or attractive");
    InsertData("Foreign", "belonging to a country other than one’s own");
    InsertData("General", "affecting or concerning all or most people places or things");
    InsertData("Generous", "showing kindness toward others");
    InsertData("Gratitude", "the quality of being thankful");
    InsertData("Judicial", "relating to or done by a court or judge");
    InsertData("Judgement", "the ability to make considered decisions or come to sensible conclusions");
    InsertData("Junior", "denoting young or younger people");
    InsertData("Grateful", "feeling or showing an appreciation of kindness");
    InsertData("Genetic", "relating to genes or heredity");
    InsertData("Gigantic", "of very great size");
    InsertData("Genre", "a style or category of art music or literature");
    InsertData("Hurry", "move or act with great speed");
    InsertData("Holy", "dedicated to God or a religious purpose");
    InsertData("Hallucination", "an experience involving the apparent perception of something not present");
    InsertData("Heavenly", "of heaven divine");
    InsertData("Charge", "demand an amount as a price from someone for a service rendered or goods supplied");
    InsertData("Categorise", "place in a particular class or group");
    InsertData("Calculate", "determine the amount or number of something mathematically");
    InsertData("Contrast", "the state of being strikingly different from something else in juxtaposition or close association");
    InsertData("Collide", "hit with force when moving");
    InsertData("Harmony", "the quality of forming a pleasing and consistent whole");
    InsertData("Hilarious", "extremely amusing");
    InsertData("Heartfelt", "sincere");
    InsertData("Harvest", "the product or result of an action");
    InsertData("Humanitarian", "concerned with or seeking to promote human welfare");
    InsertData("Highlight", "an outstanding part of an event or period of time");
    InsertData("Magnetic", "the ability to attract substances possessing a magnetic quality (eg: iron)");
    InsertData("Masculine", "having qualities or appearance traditionally associated with men");
    InsertData("Maternal", "relating to a mother");
    InsertData("Illuminate", "make something visible or bright by shining light on it");
    InsertData("Illustrate", "provide with pictures");
    InsertData("Imagination", "the action of forming new ideas or images or concepts of external objects not present to the senses");
    InsertData("Inferior", "lower in rank status or quality");
    InsertData("Impactful", "having a major effect");
    InsertData("Interior", "relating to the inside");
    InsertData("Improper", "not in accordance with accepted rules or standards");
    InsertData("Impossible", "not able to occur exist or be done");
    InsertData("Invisible", "unable to be seen");
    InsertData("Incentive", "a thing that motivates or encourages one to do something");
    InsertData("Iconic", "relating to or of the nature of an icon");
    InsertData("Jolly", "happy and cheerful");
    InsertData("Justice", "just behaviour or treatment");
    InsertData("Knowledge", "the theoretical or practical understanding of a subject");
    InsertData("Kind", "having or showing a friendly generous and considerate nature");
    InsertData("National", "relating to a nation");
    InsertData("Optimistic", "hopeful and confident about the future");
    InsertData("Optional", "available to be chosen but not obligatory");
    InsertData("Keen", "having or showing eagerness or enthusiasm");
    InsertData("Keep", "have or retain possession of");
    InsertData("Lavish", "spending or using things that are more than necessary");
    InsertData("Luxurious", "extremely comfortable elegant or enjoyable especially in a way that involves great expense");
    InsertData("Long", "lasting	enduring or having endured for a long period of time");
    InsertData("Lovable", "inspiring or deserving love or affection");
    InsertData("Late", "doing something or taking place after the expected proper or usual time");
    InsertData("Linguistic", "relating to language");
    InsertData("Legend", "an extremely famous or notorious person especially in a particular field");
    InsertData("Loot", "goods especially private property taken from an enemy in war");
    InsertData("Loud", "producing or capable of producing much noise");
    InsertData("Luminous", "giving off light");
    InsertData("Levitate", "rise or cause to rise and hover in the air especially by means of supernatural or magical power");
    InsertData("Leave", "go away from");
    InsertData("Opportunity", "a set of circumstances that makes it possible to do something");
    InsertData("Practical", "concerned with the actual doing or use of something rather than with theory and ideas");
    InsertData("Publish", "prepare and issue for public sale distribution or readership");
    InsertData("Permit", "give authorization or consent to someone to do something");
    InsertData("Marginal", "relating to or situated at the edge of something");
    InsertData("Majestic", "having or showing impressive beauty");
    InsertData("Minimal", "of a minimum amount quantity or degree");
    InsertData("Manufacturing", "producing something on a large scale using machinery");
    InsertData("Materialistic", "excessively concerned with material possessions");
    InsertData("Neighbour", "a person living near or next door");
    InsertData("Native", "associated with the place or circumstances of a person’s birth");
    InsertData("Narration", "the action or process of narrating a story");
    InsertData("Normal", "the usual or typical state or condition");
    InsertData("Objective", "something that is planned aimed at or sought");
    InsertData("Ordinary", "Without any special or distinctive features");
    InsertData("Ultimately", "in the end");
    InsertData("Victory", "an act of defeating an enemy or opponent in a battle");
    InsertData("^$#&^*", "error");
    PrintHashtable();

    printf("Meaning of \"Ultimately\" is \"%s\"\n",SearchMeaning("Ultimately"));
    printf("Meaning of \"Knowledge\" is \"%s\"\n",SearchMeaning("Knowledge"));
    printf("Meaning of \"CPU\" is \"%s\"\n",SearchMeaning("CPU"));
}